name: translation
title: "[Translation]"
description: Contribute to translations or report localization issues
labels: [translation]
assignees: []

body:
  - type: textarea
    id: location
    attributes:
      label: 📍 Location of the text
      description: Where is the translation problem or missing translation? Be specific.
      placeholder: Example: On the homepage, the Start button text.
    validations:
      required: true
  - type: textarea
    id: current
    attributes:
      label: 📝 Current text
      description: What does the current text say?
      placeholder: Example: The button currently says "Begin", which feels too formal.
    validations:
      required: true
  - type: textarea
    id: suggestion
    attributes:
      label: ✅ Suggested translation
      description: What do you think it should say instead?
      placeholder: Example: I suggest "Start" – it's more natural and widely used.
    validations:
      required: true
  - type: input
    id: language
    attributes:
      label: 🌐 Language
      description: Which language is this related to? (e.g., English, en)
      placeholder: Example: English
    validations:
      required: true
