name: Download and Deploy Release to preview branch

on:
  workflow_run:
    workflows: ["📦Auto Release"]
    types:
      - completed

permissions:
  contents: write
  id-token: write

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout preview branch
      uses: actions/checkout@v4
      with:
        ref: preview
    - name: Get latest release and download asset
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        TAG=$(gh release list --limit 1 --repo "${{ github.repository }}" | awk '{print $1}')
        gh release download "$TAG" --repo "${{ github.repository }}" --pattern "Dirlotix-*.zip"
        echo "TAG_NAME=$TAG" >> $GITHUB_ENV
    - name: Clean preview branch
      run: |
        find . -mindepth 1 ! -regex '^./\.git\(/.*\)?' -exec rm -rf {} +
    - name: Extract zip and cleanup
      run: |
        unzip Dirlotix-*.zip -d .
        rm Dirlotix-*.zip
    - name: Commit and push to preview
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add .
        git commit -m "Deploy ${{ env.TAG_NAME }} to preview" || exit 0
        git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }} HEAD:preview
